# Fichier: render.yaml
# Version corrigée avec les sections 'databases' et 'services' séparées.

# Les bases de données sont définies dans leur propre section de premier niveau.
databases:
  # Chaque base de données commence par un tiret "-".
  - name: golf-db          # Le nom de notre service de base de données.
    databaseName: golf_app_db # Le nom de la base de données réelle.
    user: golf_app_user   # L'utilisateur pour cette base.
    plan: free            # Le plan gratuit de Render.

# Les services applicatifs (notre API FastAPI) sont dans cette section.
services:
  # Notre service web.
  - name: golf-api
    type: web
    runtime: python
    plan: free
    # Utilisation de Poetry, qui est défini dans pyproject.toml.
    buildCommand: "poetry install"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DATABASE_URL
        fromDatabase:
          name: golf-db # Cette valeur doit correspondre au 'name' de la base de données ci-dessus.
          property: connectionString # Render injectera l'URL de connexion.

