# Fichier: render.yaml
# Définit l'infrastructure pour Render.com, optimisé pour le plan Pro.

services:
  # Service Web pour l'API FastAPI
  - type: web
    name: golf-api
    runtime: python
    region: frankfurt # ou une autre région, ex: oregon
    plan: pro # Plan mis à jour vers le slug correct
    # Indique à Render comment installer les dépendances
    buildCommand: "poetry install --no-root"
    # Commande de pré-déploiement pour les migrations de base de données
    preDeployCommand: "alembic upgrade head"
    # Commande pour lancer l'application avec Uvicorn
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: / # Chemin pour vérifier que l'application est bien démarrée
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: golf-db # Doit correspondre au nom de la base de données ci-dessous
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11.8

databases:
  # Base de données PostgreSQL
  - name: golf-db
    plan: pro # Plan mis à jour vers le slug correct
    # postgresqlVersion: 15 # Vous pouvez spécifier une version si besoin

