"""Changer la relation Player-Team en un-à-plusieurs

Revision ID: 20251005
Revises: 
Create Date: 2025-10-05 18:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251005'
down_revision: Union[str, None] = None # Mettez ici l'ID de votre dernière migration si vous en aviez une
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Création de la table 'teams'
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('captain_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['captain_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('captain_id')
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    
    # Ajout de la colonne 'team_id' à la table 'players'
    op.add_column('players', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_players_team_id", # Nom de la contrainte
        'players', 'teams', 
        ['team_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Inversion des opérations
    op.drop_constraint("fk_players_team_id", 'players', type_='foreignkey')
    op.drop_column('players', 'team_id')
    
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
