"""Ajoute les colonnes de détail à la table des joueurs

Revision ID: 20251006
Revises: 20251005_add_teams_relation
Create Date: 2025-10-06 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251006_add_details_to_players'
down_revision: Union[str, None] = '20251005_add_teams_relation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('players', sa.Column('email', sa.String(), nullable=True))
    op.add_column('players', sa.Column('handicap', sa.Float(), nullable=True))
    op.create_index(op.f('ix_players_email'), 'players', ['email'], unique=True)
    op.create_index(op.f('ix_players_first_name'), 'players', ['first_name'], unique=False)
    op.create_index(op.f('ix_players_handicap'), 'players', ['handicap'], unique=False)
    op.create_index(op.f('ix_players_last_name'), 'players', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_last_name'), table_name='players')
    op.drop_index(op.f('ix_players_handicap'), table_name='players')
    op.drop_index(op.f('ix_players_first_name'), table_name='players')
    op.drop_index(op.f('ix_players_email'), table_name='players')
    op.drop_column('players', 'handicap')
    op.drop_column('players', 'email')
    op.drop_column('players', 'last_name')
    op.drop_column('players', 'first_name')
    # ### end Alembic commands ###
